/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author moral
 */
public class ElementoListaArticulo extends javax.swing.JPanel {

    /**
     * Creates new form ElementoListaArticulo
     */
    public ElementoListaArticulo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombreArt = new javax.swing.JLabel();
        labelPrecioArt = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelNombreArt.setText("Prueba prueba prueba");

        labelPrecioArt.setText("Precio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(labelNombreArt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(labelPrecioArt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreArt)
                    .addComponent(labelPrecioArt))
                .addGap(5, 5, 5))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelNombreArt;
    private javax.swing.JLabel labelPrecioArt;
    // End of variables declaration//GEN-END:variables

    public void setNombreArt(String nombre) {
        labelNombreArt.setText(nombre);
    }

    public void setPrecioArt(int precio) {
        labelPrecioArt.setText(Integer.toString(precio));
        ImageIcon iconoMoneda = new ImageIcon("Imagenes/Moneda.png"); //Carga la imagen en un ImageIcon
        Image imagenMoneda = iconoMoneda.getImage(); //Lo convierte a un componente Image
        Image imagenMonedaAux = imagenMoneda.getScaledInstance(15, 15, java.awt.Image.SCALE_SMOOTH); //Escala al tamaño correcto
        iconoMoneda = new ImageIcon(imagenMonedaAux);  //Lo convierte devuelta en un ImageIcon
        labelPrecioArt.setIcon(iconoMoneda);
    }
}
