package interfaz;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author moral
 */
public class StatJugador extends javax.swing.JPanel {

    private String flecha = "→";

    /**
     * Creates new form StatJugador
     */
    public StatJugador() {
        initComponents();
        labelNombre.setText("Nombre");
    }

    public StatJugador(String nombre) {
        initComponents();
        labelNombre.setText(nombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombre = new javax.swing.JLabel();
        labelValor = new javax.swing.JLabel();
        labelFlecha = new javax.swing.JLabel();
        labelValorCambio = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        setPreferredSize(new java.awt.Dimension(250, 31));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNombre.setText("Defensa Mag.");
        add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 7, -1, -1));

        labelValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelValor.setText("10");
        add(labelValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 7, -1, -1));

        labelFlecha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelFlecha.setText("→");
        add(labelFlecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 8, -1, 13));

        labelValorCambio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelValorCambio.setText("10");
        add(labelValorCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 7, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelFlecha;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelValor;
    private javax.swing.JLabel labelValorCambio;
    // End of variables declaration//GEN-END:variables

    public void setValor(int valor) {
        labelValor.setText(Integer.toString(valor));
    }

    public void ocultarCambio() {
        labelFlecha.setText("  ");
        labelValorCambio.setText("   ");
    }

    //Muestra los stats despues de equipar un objeto
    public void mostrarCambio(int nuevoValor) {
        int valorActual = Integer.valueOf(labelValor.getText());
        labelValorCambio.setText(Integer.toString(nuevoValor));
        //Cambia el color del nuevo valor segun si es mayor o menor
        if (nuevoValor > valorActual) {
            labelValorCambio.setForeground(Color.GREEN);
        } else if (nuevoValor < valorActual) {
            labelValorCambio.setForeground(Color.RED);
        } else {
            labelValorCambio.setForeground(Color.BLACK);
        }
        labelFlecha.setText(flecha);
    }
}
