package interfaz;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTabbedPane;
import javax.swing.JTextArea;

/**
 *
 * @author moral
 */
public class TiendaVentana extends javax.swing.JFrame {

    private boolean modoComprar = true;
    private final String descripArtDefault = "	        Seleccione un artículo para ver más detalles.",
            nombreArtDefault = " ";

    /**
     * Creates new form TiendaVentana
     */
    public TiendaVentana() {
        initComponents();
        this.setTitle("Tienda RPG");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPestanasArt = new javax.swing.JTabbedPane();
        panelScrollComprar = new javax.swing.JScrollPane();
        listaComprar = new javax.swing.JList();
        panelScrollVender = new javax.swing.JScrollPane();
        listaVender = new javax.swing.JList();
        panelJugador = new javax.swing.JPanel();
        iconoJug = new javax.swing.JLabel();
        labelJugNombre = new javax.swing.JLabel();
        labelJugDinero = new javax.swing.JLabel();
        ImageIcon iconoMoneda = new ImageIcon("Imagenes/Moneda.png"); //Carga la imagen en un ImageIcon
        Image imagenMoneda = iconoMoneda.getImage(); //Lo convierte a un componente Image
        Image imagenMonedaAux = imagenMoneda.getScaledInstance(15, 15, java.awt.Image.SCALE_SMOOTH); //Escala al tamaño correcto
        iconoMoneda = new ImageIcon(imagenMonedaAux);  //Lo convierte devuelta en un ImageIcon
        labelJugDinero.setIcon(iconoMoneda);
        statAta = new interfaz.StatJugador("Ataque");
        statDef = new interfaz.StatJugador("Defensa");
        statAtaMag = new interfaz.StatJugador("Ataque Mág.");
        statDefMag = new interfaz.StatJugador("Velocidad");
        statVel = new interfaz.StatJugador("Defensa Mág.");
        panelArt = new javax.swing.JPanel();
        labelNombreArt = new javax.swing.JLabel();
        panelScrollDescrip = new javax.swing.JScrollPane();
        textoDescrip = new javax.swing.JTextArea();
        labelEquipado = new javax.swing.JLabel();
        labelEquipadoValor = new javax.swing.JLabel();
        labelCantidad = new javax.swing.JLabel();
        labelCantidadValor = new javax.swing.JLabel();
        botonComprarVender = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tienda RPG");
        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(600, 800));
        setMinimumSize(new java.awt.Dimension(50, 50));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 600));

        panelPestanasArt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelPestanasArt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelPestanasArt.setPreferredSize(new java.awt.Dimension(298, 473));
        panelPestanasArt.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CambiarModoTienda(evt);
            }
        });

        listaComprar.setBackground(new java.awt.Color(153, 153, 153));
        listaComprar.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaComprar.setSelectionBackground(new java.awt.Color(204, 204, 204));
        listaComprar.setSelectionForeground(new java.awt.Color(0, 0, 0));
        panelScrollComprar.setViewportView(listaComprar);

        panelPestanasArt.addTab("Comprar", panelScrollComprar);

        listaVender.setBackground(new java.awt.Color(153, 153, 153));
        listaVender.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        panelScrollVender.setViewportView(listaVender);

        panelPestanasArt.addTab("Vender", panelScrollVender);

        panelJugador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelJugador.setMinimumSize(new java.awt.Dimension(300, 475));
        panelJugador.setPreferredSize(new java.awt.Dimension(300, 475));

        iconoJug.setIcon(new ImageIcon("Imagenes/NinjaHead.png"));

        labelJugNombre.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelJugNombre.setText("Nombre");

        labelJugDinero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelJugDinero.setText("Dinero");

        javax.swing.GroupLayout panelJugadorLayout = new javax.swing.GroupLayout(panelJugador);
        panelJugador.setLayout(panelJugadorLayout);
        panelJugadorLayout.setHorizontalGroup(
            panelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJugadorLayout.createSequentialGroup()
                .addGroup(panelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelJugadorLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(iconoJug, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelJugNombre)
                            .addComponent(labelJugDinero)))
                    .addGroup(panelJugadorLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(panelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statVel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statDefMag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statAtaMag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statDef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statAta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
        );

        panelJugadorLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {statAta, statAtaMag, statDef, statDefMag, statVel});

        panelJugadorLayout.setVerticalGroup(
            panelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJugadorLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelJugadorLayout.createSequentialGroup()
                        .addComponent(labelJugNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelJugDinero))
                    .addComponent(iconoJug, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(statAta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(statDef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(statAtaMag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(statVel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(statDefMag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        panelJugadorLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {statAta, statAtaMag, statDef, statDefMag, statVel});

        panelArt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelArt.setPreferredSize(new java.awt.Dimension(598, 123));

        labelNombreArt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelNombreArt.setText(" ");

        panelScrollDescrip.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        textoDescrip.setEditable(false);
        textoDescrip.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textoDescrip.setLineWrap(true);
        textoDescrip.setText("\t        Seleccione un artículo para ver más detalles.");
        textoDescrip.setWrapStyleWord(true);
        textoDescrip.setOpaque(false);
        panelScrollDescrip.setViewportView(textoDescrip);

        labelEquipado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelEquipado.setText(" ");

        labelEquipadoValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelEquipadoValor.setText(" ");

        labelCantidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCantidad.setText(" ");

        labelCantidadValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCantidadValor.setText(" ");

        botonComprarVender.setBackground(new java.awt.Color(204, 204, 204));
        botonComprarVender.setText("Comprar");

        javax.swing.GroupLayout panelArtLayout = new javax.swing.GroupLayout(panelArt);
        panelArt.setLayout(panelArtLayout);
        panelArtLayout.setHorizontalGroup(
            panelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelArtLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelScrollDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelArtLayout.createSequentialGroup()
                        .addComponent(labelEquipado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelEquipadoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(labelCantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelCantidadValor, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addGap(82, 82, 82)
                        .addComponent(botonComprarVender, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelNombreArt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelArtLayout.setVerticalGroup(
            panelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArtLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(labelNombreArt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelScrollDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(panelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonComprarVender)
                    .addComponent(labelCantidadValor)
                    .addComponent(labelEquipado)
                    .addComponent(labelEquipadoValor)
                    .addComponent(labelCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelArt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(panelPestanasArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(panelJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPestanasArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(panelArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CambiarModoTienda(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CambiarModoTienda
        JTabbedPane panelPestanas = (JTabbedPane) evt.getSource();
        if (panelPestanas.getSelectedIndex() == 1) {
            modoComprar = false;
            botonComprarVender.setText("Vender");
            listaVender.getSelectionModel().clearSelection();
        } else {
            modoComprar = true;
            botonComprarVender.setText("Comprar");
            listaComprar.getSelectionModel().clearSelection();
        }
        cambiarVisibilidadDescripcion(false);
        ocultarCambioStats();
    }//GEN-LAST:event_CambiarModoTienda

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonComprarVender;
    private javax.swing.JLabel iconoJug;
    private javax.swing.JLabel labelCantidad;
    private javax.swing.JLabel labelCantidadValor;
    private javax.swing.JLabel labelEquipado;
    private javax.swing.JLabel labelEquipadoValor;
    private javax.swing.JLabel labelJugDinero;
    private javax.swing.JLabel labelJugNombre;
    private javax.swing.JLabel labelNombreArt;
    private javax.swing.JList listaComprar;
    private javax.swing.JList listaVender;
    private javax.swing.JPanel panelArt;
    private javax.swing.JPanel panelJugador;
    private javax.swing.JTabbedPane panelPestanasArt;
    private javax.swing.JScrollPane panelScrollComprar;
    private javax.swing.JScrollPane panelScrollDescrip;
    private javax.swing.JScrollPane panelScrollVender;
    private interfaz.StatJugador statAta;
    private interfaz.StatJugador statAtaMag;
    private interfaz.StatJugador statDef;
    private interfaz.StatJugador statDefMag;
    private interfaz.StatJugador statVel;
    private javax.swing.JTextArea textoDescrip;
    // End of variables declaration//GEN-END:variables

    public JList getListaComprar() {
        return listaComprar;
    }

    public JList getListaVender() {
        return listaVender;
    }

    public JButton getBotonComprarVender() {
        return botonComprarVender;
    }

    public JLabel getLabelCantidadValor() {
        return labelCantidadValor;
    }
       
    public JLabel getLabelEquipadoValor() {
        return labelEquipadoValor;
    }

    public JLabel getLabelNombreArt() {
        return labelNombreArt;
    }

    public JTextArea getTextoDescrip() {
        return textoDescrip;
    }

    public boolean isModoComprar() {
        return modoComprar;
    }

    public void setNombreJugador(String nombre) {
        labelJugNombre.setText(nombre);
    }

    public void setDineroJugador(int monto) {
        labelJugDinero.setText(Integer.toString(monto));
    }

    public void setStatAtaque(int ataque) {
        statAta.setValor(ataque);
    }

    public void setStatDefensa(int def) {
        statDef.setValor(def);
    }

    public void setStatAtaqueMag(int atMag) {
        statAtaMag.setValor(atMag);
    }

    public void setStatDefensaMag(int defMag) {
        statDefMag.setValor(defMag);
    }

    public void setStatVelocidad(int vel) {
        statVel.setValor(vel);
    }

    public void cambiarVisibilidadDescripcion(boolean visible) {
        if (visible) {
            labelCantidad.setText("Cantidad:");
            labelEquipado.setText("Equipado:");
        } else {
            textoDescrip.setText(descripArtDefault);
            labelNombreArt.setText(nombreArtDefault);
            labelCantidad.setText(" ");
            labelCantidadValor.setText(" ");
            labelEquipado.setText(" ");
            labelEquipadoValor.setText(" ");
        }
    }

    public void mostrarCambioStats(int ata, int def, int ataMag, int defMag, int vel) {
        statAta.mostrarCambio(ata);
        statDef.mostrarCambio(def);
        statAtaMag.mostrarCambio(ataMag);
        statDefMag.mostrarCambio(defMag);
        statVel.mostrarCambio(vel);
    }

    public void ocultarCambioStats() {
        statAta.ocultarCambio();
        statDef.ocultarCambio();
        statAtaMag.ocultarCambio();
        statDefMag.ocultarCambio();
        statVel.ocultarCambio();
    }
}
